// <auto-generated />
using System;
using DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(CoffeeDbContext))]
    [Migration("20231122185314_migration")]
    partial class migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DAL.Models.Ban", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("bans");
                });

            modelBuilder.Entity("DAL.Models.Ban_HD", b =>
                {
                    b.Property<Guid?>("IdBan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdHd")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdBan", "IdHd");

                    b.HasIndex("BanId");

                    b.HasIndex("HoaDonId");

                    b.ToTable("ban_HDs");
                });

            modelBuilder.Entity("DAL.Models.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdKm")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdNv")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KhuyenMaiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NhanVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TongTien")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhuyenMaiId");

                    b.HasIndex("NhanVienId");

                    b.ToTable("hoaDons");
                });

            modelBuilder.Entity("DAL.Models.KhuyenMai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DkGiam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PhamTramGiam")
                        .HasColumnType("int");

                    b.Property<int>("SoTienGiam")
                        .HasColumnType("int");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("khuyenMais");
                });

            modelBuilder.Entity("DAL.Models.LoaiSp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("loaiSps");
                });

            modelBuilder.Entity("DAL.Models.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChucVu")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaiKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("nhanViens");
                });

            modelBuilder.Entity("DAL.Models.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GiaBan")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdLoai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LoaiSpId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoaiSpId");

                    b.ToTable("sanPhams");
                });

            modelBuilder.Entity("DAL.Models.SP_HD", b =>
                {
                    b.Property<Guid?>("IdSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<Guid?>("HoaDonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdHd")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SanPhamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdSp");

                    b.HasIndex("HoaDonId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("sP_HDs");
                });

            modelBuilder.Entity("DAL.Models.Ban_HD", b =>
                {
                    b.HasOne("DAL.Models.Ban", "Ban")
                        .WithMany("Ban_HDs")
                        .HasForeignKey("BanId");

                    b.HasOne("DAL.Models.HoaDon", "HoaDon")
                        .WithMany("Ban_HDs")
                        .HasForeignKey("HoaDonId");

                    b.Navigation("Ban");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("DAL.Models.HoaDon", b =>
                {
                    b.HasOne("DAL.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("HoaDons")
                        .HasForeignKey("KhuyenMaiId");

                    b.HasOne("DAL.Models.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("NhanVienId");

                    b.Navigation("KhuyenMai");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("DAL.Models.SanPham", b =>
                {
                    b.HasOne("DAL.Models.LoaiSp", "LoaiSp")
                        .WithMany("SanPhams")
                        .HasForeignKey("LoaiSpId");

                    b.Navigation("LoaiSp");
                });

            modelBuilder.Entity("DAL.Models.SP_HD", b =>
                {
                    b.HasOne("DAL.Models.HoaDon", "HoaDon")
                        .WithMany("SP_HDs")
                        .HasForeignKey("HoaDonId");

                    b.HasOne("DAL.Models.SanPham", "SanPham")
                        .WithMany("SP_HDs")
                        .HasForeignKey("SanPhamId");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("DAL.Models.Ban", b =>
                {
                    b.Navigation("Ban_HDs");
                });

            modelBuilder.Entity("DAL.Models.HoaDon", b =>
                {
                    b.Navigation("Ban_HDs");

                    b.Navigation("SP_HDs");
                });

            modelBuilder.Entity("DAL.Models.KhuyenMai", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("DAL.Models.LoaiSp", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("DAL.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("DAL.Models.SanPham", b =>
                {
                    b.Navigation("SP_HDs");
                });
#pragma warning restore 612, 618
        }
    }
}
